### ISSUE TITLE
Error when trying to tag files

### ISSUE THREAD

**Issue by BasicMiniTacos** [bpepple/metron#231]
-o creates the following error on my Windows install:

Starting online search and tagging:
----------------------------------
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\metron-tagger.exe\__main__.py", line 7, in <module>
  File "C:\Users\Matt\AppData\Roaming\Python\Python312\site-packages\metrontagger\cli.py", line 64, in main
    runner.run()
  File "C:\Users\Matt\AppData\Roaming\Python\Python312\site-packages\metrontagger\run.py", line 322, in run
    t.identify_comics(file_list, self.config)
  File "C:\Users\Matt\AppData\Roaming\Python\Python312\site-packages\metrontagger\talker.py", line 296, in identify_comics
    issue_id, multiple_match = self._process_file(fn, config.interactive)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matt\AppData\Roaming\Python\Python312\site-packages\metrontagger\talker.py", line 161, in _process_file
    source, id_ = self._get_source_id(md)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matt\AppData\Roaming\Python\Python312\site-packages\metrontagger\talker.py", line 127, in _get_source_id
    lower_notes = md.notes.lower()
                  ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'

Windows 11. Running out of both cmd and Powershell

**Comment by bpepple** [comment]
Closing this since it's for the wrong product, but I've opened one for Metron-Talker.
 https://github.com/Metron-Project/metron-tagger/issues/113
